import InclusionQuantum.Normalization

/-!
# Two unentangled quantum witnesses

QMA2 uses two separately normalized pure states and their explicit tensor
product. The soundness quantifier ranges over all such pairs, never over an
arbitrary joint entangled state. Both witness lengths and the ancilla length
are fixed polynomials; the complete circuit is generated by the existing
concrete polynomial-time transducer. The gap holds on every binary input.

The use of pure product witnesses, fixed 2/3 versus 1/3 thresholds, and two
possibly different polynomial witness lengths is the intended total-language
restriction of QMA(2). Equivalence to formulations allowing separable mixed
states, general gates, or other inverse-polynomial gaps is trusted literature,
not a theorem proved here. See Harrow and Montanaro, Testing product states,
quantum Merlin-Arthur games and tensor optimisation (JACM 2013):
https://arxiv.org/abs/1001.0017 .
-/

namespace InclusionBench.Quantum

open scoped BigOperators
open Counting (polynomialValue)

noncomputable section

def splitBasis {left right : Nat} (basis : Basis (left + right)) :
    Basis left × Basis right :=
  (fun index => basis ⟨index.val, by omega⟩,
   fun index => basis ⟨left + index.val, by omega⟩)

def joinBasis {left right : Nat} (pair : Basis left × Basis right) :
    Basis (left + right) :=
  fun index => if h : index.val < left then pair.1 ⟨index.val, h⟩
    else pair.2 ⟨index.val - left, by omega⟩

theorem join_split_basis {left right : Nat} (basis : Basis (left + right)) :
    joinBasis (splitBasis basis) = basis := by
  funext index
  dsimp [joinBasis, splitBasis]
  split
  · rfl
  · congr 1
    apply Fin.ext
    dsimp
    omega

theorem split_join_basis {left right : Nat} (pair : Basis left × Basis right) :
    splitBasis (joinBasis pair) = pair := by
  apply Prod.ext
  · funext index
    simp [splitBasis, joinBasis]
  · funext index
    simp [splitBasis, joinBasis, show ¬ left + index.val < left by omega]

def splitBasisEquiv (left right : Nat) : Basis (left + right) ≃ Basis left × Basis right where
  toFun := splitBasis
  invFun := joinBasis
  left_inv := join_split_basis
  right_inv := split_join_basis

def productState {left right : Nat} (first : State left) (second : State right) :
    State (left + right) :=
  fun basis => first (splitBasis basis).1 * second (splitBasis basis).2

theorem productState_normSquared {left right : Nat}
    (first : State left) (second : State right) :
    normSquared (productState first second) = normSquared first * normSquared second := by
  classical
  calc
    normSquared (productState first second) =
        ∑ pair : Basis left × Basis right,
          Complex.normSq (first pair.1) * Complex.normSq (second pair.2) := by
      simpa only [normSquared, productState, Complex.normSq_mul, splitBasisEquiv]
        using (splitBasisEquiv left right).bijective.sum_comp
          (fun pair => Complex.normSq (first pair.1) * Complex.normSq (second pair.2))
    _ = normSquared first * normSquared second := by
      rw [Fintype.sum_prod_type]
      simp_rw [← Finset.mul_sum]
      rw [← Finset.sum_mul]
      rfl

theorem productState_normalized {left right : Nat}
    (first : State left) (second : State right)
    (first_normalized : Normalized first) (second_normalized : Normalized second) :
    Normalized (productState first second) := by
  unfold Normalized at *
  rw [productState_normSquared, first_normalized, second_normalized, one_mul]

abbrev TwoWitnessFamily (firstLength secondLength ancillaLength : List Nat) :=
  (n : Nat) → Circuit (n + (polynomialValue firstLength n + polynomialValue secondLength n) +
    polynomialValue ancillaLength n + 1)

def twoWitnessAcceptance {firstLength secondLength ancillaLength : List Nat}
    (family : TwoWitnessFamily firstLength secondLength ancillaLength) (input : Word)
    (first : State (polynomialValue firstLength input.length))
    (second : State (polynomialValue secondLength input.length)) : ℝ :=
  (family input.length).acceptanceProbability
    (initialState input
      (polynomialValue firstLength input.length + polynomialValue secondLength input.length)
      (polynomialValue ancillaLength input.length) (productState first second))

def QMA2 : ComplexityClass :=
  fun L => ∃ firstLength secondLength ancillaLength : List Nat,
    ∃ family : TwoWitnessFamily firstLength secondLength ancillaLength,
    polynomialUniform family ∧ ∀ input,
      (L input → ∃ first : State (polynomialValue firstLength input.length),
        ∃ second : State (polynomialValue secondLength input.length),
        Normalized first ∧ Normalized second ∧
        2 ≤ 3 * twoWitnessAcceptance family input first second) ∧
      (¬ L input → ∀ first : State (polynomialValue firstLength input.length),
        ∀ second : State (polynomialValue secondLength input.length),
        Normalized first → Normalized second →
        3 * twoWitnessAcceptance family input first second ≤ 1)

theorem twoWitnessAcceptance_bounded {firstLength secondLength ancillaLength : List Nat}
    (family : TwoWitnessFamily firstLength secondLength ancillaLength) (input : Word)
    (first : State (polynomialValue firstLength input.length))
    (second : State (polynomialValue secondLength input.length))
    (first_normalized : Normalized first) (second_normalized : Normalized second) :
    0 ≤ twoWitnessAcceptance family input first second ∧
      twoWitnessAcceptance family input first second ≤ 1 := by
  exact acceptanceProbability_bounded _ _
    (initialState_preserves_normalized input _ _ _
      (productState_normalized first second first_normalized second_normalized))

end
end InclusionBench.Quantum
