"""Keep the Lean vocabulary and scored roster bound to data/classes.json."""
from __future__ import annotations

import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def render(catalog: dict) -> str:
    context = [item["id"] for item in catalog["classes"]]
    scored = catalog.get("scored_class_ids", context)
    if (not context or len(set(context)) != len(context) or
            any(not isinstance(name, str) or not re.fullmatch(r"[A-Za-z][A-Za-z0-9]*", name)
                for name in context)):
        raise ValueError("Invalid inference vocabulary")
    if (not isinstance(scored, list) or not scored or
            any(not isinstance(name, str) for name in scored) or
            len(set(scored)) != len(scored) or not set(scored) <= set(context)):
        raise ValueError("Invalid scored roster")

    def names(values):
        rows = [", ".join("." + name for name in values[start:start + 10])
                for start in range(0, len(values), 10)]
        return "[" + ",\n   ".join(rows) + "]"

    constructors = "\n  | ".join(" | ".join(context[start:start + 10])
                               for start in range(0, len(context), 10))

    return f'''-- Generated by scripts/generate_catalog.py from data/classes.json.
import InclusionBench.Certificate
import InclusionBench.Scoring

namespace InclusionBench

/-- Names for the full inference vocabulary, including unscored background
classes. Concrete meanings are supplied by the operational interpretation. -/
inductive ClassId where
  | {constructors}
  deriving DecidableEq, BEq, Repr, Lean.ToJson, Lean.FromJson

def allClasses : List ClassId :=
  {names(context)}

/-- Only these endpoints participate in the scored matrix. -/
def scoredClasses : List ClassId :=
  {names(scored)}

theorem catalog_size : allClasses.length = {len(context)} := rfl

theorem catalog_no_duplicates : allClasses.eraseDups = allClasses := by decide

theorem every_class_catalogued (id : ClassId) : id ∈ allClasses := by
  cases id <;> simp [allClasses]

theorem roster_size : scoredClasses.length = {len(scored)} := rfl

theorem roster_no_duplicates : scoredClasses.eraseDups = scoredClasses := by decide

theorem scored_class_in_catalog (id : ClassId) (_ : id ∈ scoredClasses) :
    id ∈ allClasses := every_class_catalogued id

def allOrderedPairs : List (OrderedPair ClassId) :=
  scoredClasses.flatMap (fun left => scoredClasses.map (fun right => (left, right)))

theorem full_matrix_size : allOrderedPairs.length = {len(scored) ** 2} := by
  simp only [allOrderedPairs, List.length_flatMap, List.length_map, roster_size]
  rfl

theorem full_matrix_score_bound (isResolved : OrderedPair ClassId → Bool) :
    score allOrderedPairs isResolved ≤ {len(scored) ** 2} := by
  have bound := score_bound_by_input_length allOrderedPairs isResolved
  simpa only [full_matrix_size] using bound

end InclusionBench
'''


def build(root: Path = ROOT) -> None:
    catalog = json.loads((root / "data/classes.json").read_text())
    (root / "lean/InclusionBench/Catalog.lean").write_text(render(catalog))


if __name__ == "__main__":
    build()
